name: Continuous Integration and Delivery

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  testing-docker-compose:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - uses: actions/checkout@v2
      - name: Build the stack
        run: docker compose  -f compose.yaml up -d --build

      - name: Get docker logs
        run: docker ps

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push to dockerhub
        run: |
          docker compose push

      - name: stop containers
        run: docker compose -f compose.yaml down --volumes

      - name: Executing remote  command and deployment to digital ocean for dev enviroment
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST}}
          USERNAME: ${{ secrets.NAME}}
          PORT: 22
          KEY: ${{ secrets.DO_PRIVATE_KEY}}
          script: |
            cd philo/
            docker system prune -af
            docker compose  -f compose.yaml down --volumes
            echo "${{secrets.DOCKER_PASSWORD}}" | docker login -u ${{secrets.DOCKER_USERNAME}} --password-stdin
            docker system prune -af
            docker compose -f compose.yaml pull
            docker compose -f compose.yaml  up --build --remove-orphans -d --force-recreate
            # docker-compose -f compose.yaml up  --build  -d