services: 
  api: 
    build:
      context: . 
    image: manulangat/blog_by_langat:com
    ports: 
      - "8000:8000"
    env_file:
      - .env.local
    volumes:
      - static_volume:/code/static
      - media_volume:/code/media

volumes:
  static_volume:
  media_volume: