# Generated by Django 2.2.6 on 2020-03-13 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_itemvariation_variation'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='pic1',
            field=models.ImageField(blank=True, null=True, upload_to='articles/'),
        ),
        migrations.AddField(
            model_name='item',
            name='pic2',
            field=models.ImageField(blank=True, null=True, upload_to='articles/'),
        ),
    ]
