# Generated by Django 2.2.6 on 2020-05-04 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20200313_2132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(blank=True, choices=[('HOME', 'HOME'), ('OFFICE', 'OFFICE'), ('LUXURY', 'LUXURY')], max_length=10, null=True),
        ),
    ]
